### ISSUE TITLE
Simplify and streamline command-line options

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-cli#24]
We have a number of use cases that are served only by knowing specific combinations of arguments with `--prefix`es. Let's make an effort to simplify common use cases like:

- creating a new job (Both create and init)
- starting or stopping a job
- listing workflows and configurations config

This may involve renaming options/parameters, and I think in some  cases it makes sense to switch to positional parameters, like for `--tag` when that applies. The tag is central to the command when it applies, and I think the prefix clouds that.

**Comment by dleehr** [comment]
Open for discussion

**Comment by dleehr** [comment]
Note in reviewing #23. It added `bespin jobs create --dry-run <file>`. I believe `create` is on the table for reorganizing, and the validation functionality is better served by something like `bespin job validate <file.yaml>`

**Comment by johnbradley** [comment]
I like the idea of streamlining the options. 
Initially I wasn't sure that tag would catch on, but after using it for a while it seems like the only way you would want to reference a workflow configuration.

**Comment by johnbradley** [comment]
Changes based on discussion with @dleehr.
Top level commands will have long and short single noun names:
- `bespin workflow` or bespin wf` lists and creates Workflows
- `bespin workflow-version` or bespin wfv` lists and creates WorkflowVersions
- `bespin workflow-config` or bespin wfc` lists and creates WorkflowConfigurations and shows job order
- `bespin share-group` or `bespin sg` lists ShareGroups
- `bespin vm-config` or `bespin vmc` lists VirtualMachineConfigurations
- `bespin job-template` or `bespin jt` will create a job template file
- `bespin job` or `bespin j` will run and manage Jobs

## `bespin workflow` commands
- `bespin workflow list (--short) (--all) (tag)` - lists workflows
  - By default it shows only current WorkflowVersion. If `--all` is specified it shows all versions
  - By default this command shows workflow versions and config. If `--shortBy` is specified this command will only show top level workflow info (name and tag).
- `bespin workflow create --name <somename> --tag <sometag>` creates a new workflow

## `bespin workflow-version` commands
- `bespin workflow-version list (--workflow tag)` - lists workflow versions
- `bespin workflow-version create --workflow <tag> --url <http...> --desc <text> --version <number or 'auto'>`

## `bespin workflow-configuration` commands
- `bespin workflow-configuration list (--workflow tag)` - lists workflow configurations
- `bespin workflow-configuration show-job-order --tag tag --workflow tag` - shows job order for specified workflow configuration
- `bespin workflow-configuration create --workflow <tag> --default-vm-strategy <name> --share-group <name> --tag <newtag> (job-order.json)` creates a new workflow version
