### ISSUE TITLE
Enhancements to bespin job validate

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-cli#27]
In creating a job for exomeseq-gatk4, I noticed the validation code doesn't catch missing fields or an empty `job_order`.

For example, with the `library` field, validation calls out when this still has a placeholder:

When the placeholder is left in, that's a `error.

> ```
> fund_code: 000
> job_order:
>   library: <String Value>
> name: TEST01
> tag: wes-gatk4/v1/gatk4-b37-human-xgen
> ```

```
Please fill in placeholder values for field(s): job_order.library
```

But if I remove the field entirely, the validation succeeds:

> ```
> fund_code: 000
> job_order: {}
> name: TEST01
> tag: wes-gatk4/v1/gatk4-b37-human-xgen
> ```

```
Job file is valid.
```

I noticed this because I put the `study_type` field in the wrong place. Validation didn't catch that and my job failed after staging the data.

**Comment by johnbradley** [comment]
Since we have moved the generation of the job-template( and thereby placeholder values) to bespin-api, that would be the better place to validate a job-template. We could add `job-templates/validate` endpoint to the bespin v2 API and just call that from bespin-cli.
